//private static final String RESULT_EIPM = "BPM"; // int 
//private static final String RESULT_PR = "PR"; // int 
//private static final String RESULT_QRS = "ORS"; // int 
//private static final String RESULT RR = "RR"; // int 
//private static final String RESULT_QT = "QT"; // int 
//private static final String RESULT_QTC = "QTC"; // int 
//public static final String RECORD_EXTERNAL_SPEED = "SPEED"; //int 
//public static final String RECORD_EXTERNAL_LENGTH = "LENGTH"; //int 
//public static final String RECORD_EXTERNAL_ZOOM = "ZOOM"; //int 
//public static final String RECORD_EXTERNAL_AUTOSTART = "AUTOSTART"; //bool 
//public static final String RECORD_EXTERNAL_FREQUENCY = "FREQUENCY"; //int 
//public static final String RECORD_EXTERNAL_SYMPTOM = "SYMPTOM"; //string 
//private static final String RESULT_RAW DATA D1 = "dataD1"; // float[] 
//private static final String RESULT_RAW_DAVA_D2 = "dataD2"; // float[] 
//private static final String RESULT_RAW DATA_D3 = "dataD3"; // float[] 
//private static final String RESULT_RAW_DATA_V1 = "dataV1"; // float[] 
//private static final String RESULT_RAW_DATA_V2 = "dataV2"; // float[] 
//private static final String RESULT_RAW_DATA_V3 = "dataV3"; // float[] 
//private static final String RESULT_RAW DATA V4 = "dataV4"; // float() 
//private static final String RESULT_RAW_DATA_VS = "dataV5"; // float[] 
//private static final String RESULT_RAW_DATA_V6 = "dataV6"; // float[] 
//private static final String RESULT_RAW_DATA_AVR = "dataAVR"; // float[] 
//private static final String RESULT_RAW_DATA_AVL = "dataAVL"; // float[] 
//private static final String RESULT_RAW DATA_AVF = "dataAVF"; // float[] 
//public static final String RECORD_EXTERNAL_PDF_PATH = "PDFPATH"; //strin. 